name = input ("Give me a name ")
name2 = input ("Give me a name  ")
adj = input ("Give me an adjective ")
adj2 = input ("Give me an adjective ")
noun = input ("Give me a noun  ")
noun2 = input ("Give me a noun ")
noun3 = input ("Give me a noun ")
noun4 = input ("Give me a noun ")
famous = input ("Give me a name of a Harry twinkle29 ")

print(name + "is with " + name2 + ". " + name + " is eating the " + adj + " " + noun + ".")

print(" So the time was 2929 and " + name + "were dying from pollution so Gojo helped humankind but the demons came out of hell and when they needed him the most he vanished")
print  ("Now a kid was born with " + adj + " powers to stop the demons from killing people but his parents hid his talents away so Harry twinkle29. ")
print  (name + "was about to get murdered but" + famous + "thankfully saved him " + name + "said he would destroy the world" )
print (name + "had died" "everyone came to mourn his death and"  +famous + " ""got taken away forever for failing his duty the end")